name: aligner
channels:
  - conda-forge
dependencies:
  - python=3.10
  - montreal-forced-aligner
  - librosa
  - pysoundfile
  - pip
  - pip:
      - flask
      - flask-cors
      - praat-parselmouth